// LUNA Workflow Backup - Generated by inspect_workflow.py
// This script recreates the complete workflow graph with all node properties and relationships.
// Run this script to restore the workflow if the graph database gets wiped.

// WARNING: This will delete all existing STEP nodes and NEXT relationships
// Uncomment the following lines to execute the deletion:
// MATCH (s:STEP) DETACH DELETE s;

// Create STEP nodes
CREATE (root:STEP {
    id: 'root', 
    description: 'Root node for conversation loop'
})

CREATE (request:STEP {
    id: 'request',
    function: 'utils.request.request',
    description: 'Get user input with dynamic prompt',
    input: '{"prompt": "@{SESSION_ID}.generate.followup|GM! How can I help?"}'
})

CREATE (generate:STEP {
    id: 'generate',
    function: 'utils.generate.generate',
    description: 'Generate response and followup question with conversation history',
    input: '{"model": "gpt-4o", "temperature": 0.7, "include_history": true, "system": "You are a helpful assistant engaged in an ongoing conversation. Maintain full context of the conversation history when responding. Reference previous messages when appropriate. Don\'t repeat information that has already been discussed unless it\'s to build upon it. Be INCREDIBLY brief.", "schema": {"type": "object", "properties": {"response": {"type": "string", "description": "A helpful and informative response to the user\'s query that directly addresses their question or request, building upon previous conversation context"}, "followup": {"type": "string", "description": "A natural followup question that builds on the conversation context and helps deepen the discussion"}, "merits_followup": {"type": "boolean", "description": "Whether the conversation warrants continuation - true if there are meaningful directions to explore, false if the conversation has reached a natural conclusion. If the user responds with a flat no then it is likely an end to the conversation, but this should be assessed within the conversational context."}, "is_movie_question": {"type": "boolean", "description": "Whether the user\'s query is about a movie or actor. Return true if the query mentions or asks about any movie, film, actor, director, or other film-related topics."}}, "required": ["response", "followup", "merits_followup", "is_movie_question"]}, "user": "@{SESSION_ID}.request.response"}'
})

CREATE (send_farewell:STEP {
    id: 'send-farewell',
    function: 'utils.reply.reply',
    description: 'Send farewell message',
    input: '{"message": "okay, GN!"}'
})

CREATE (reply:STEP {
    id: 'reply',
    function: 'utils.reply.reply',
    description: 'Send response to user',
    input: '{"message": "@{SESSION_ID}.generate.response ...Followup? @{SESSION_ID}.generate.merits_followup"}'
})

CREATE (reply_offensive:STEP {
    id: 'reply-offensive',
    function: 'utils.reply.reply',
    input: '{"message": "fuck alright then! @{SESSION_ID}.generate.response"}'
})

// Create NEXT relationships
CREATE (root)-[:NEXT]->(request)
CREATE (request)-[:NEXT]->(generate)
CREATE (generate)-[:NEXT {condition: '[{"false":"@{SESSION_ID}.generate.merits_followup"}]'}]->(send_farewell)
CREATE (generate)-[:NEXT {condition: '[{"true":"@{SESSION_ID}.generate.merits_followup"}]'}]->(reply)
CREATE (reply)-[:NEXT]->(request); 